language: node_js
node_js:
  - "0.10"
  - "0.12"

branches:
  only:
    - master

addons:
  - postgresql: "9.3"

install:
  - npm install chai mocha should supertest --save-dev
  - npm install body-parser coffee-script debug ejs express morgan node-compass serve-favicon bootstrap pg
  - npm i --save-dev mocha-jsdom

before_script:
  - psql -c 'create database freyrcms_development;' -U postgres

script:
  - npm test