language: node_js
node_js:
  - "0.10"
  - "0.12"
install:
  - npm install chai mocha should supertest --save-dev
  - npm install body-parser coffee-script debug ejs express morgan node-compass serve-favicon

script:
  - npm test